### ISSUE TITLE
Pip Install -> Unable to start due to Max Version Restriction

### ISSUE THREAD

**Issue by jvanderaa** [FragmentedPacket/nautobot-eox-notices#11]
### Environment
* Python version:  3.6.9
* Nautobot version:  1.0.2
* nautobot-eox-notices version:  0.1.0

### Expected Behavior

Start Nautobot with the plugin installed

### Observed Behavior

```
nautobot-server[46920]: nautobot.extras.plugins.exceptions.PluginImproperlyConfigured: Plugin eox_notices requires Nautobot maximum version 1.0.0b3
```
Error on startup

### Steps to Reproduce
1. Install via pip
2. Restart services

**Comment by FragmentedPacket** [comment]
Fixed with a new release v0.1.1
